import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoadingScreen from "../components/ui/loading";
import PreFooter from "@/components/ui/pre-footer";
import Footer from "@/components/ui/footer";
import Cursor from "@/components/ui/cursor";
import CustomScrollbar from "@/components/ui/customScrollbar";
import Navbar from "@/components/ui/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        id="top"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomScrollbar />
        <Navbar />
        <Cursor />
        <LoadingScreen />
        {children}
        <PreFooter />
        <Footer />
      </body>
    </html>
  );
}
